import { useEffect, useState } from "react";
import type { NextPage } from "next";
import Head from "next/head";
import { connect } from "socket.io-client";
import styles from "../styles/Home.module.css";

const socket = connect("http://localhost:3000");

const Home: NextPage = () => {
  const [message, setMessage] = useState<string>("");

  useEffect(() => {
    if (!socket) return;

    socket.on("connect", () => {
      console.log("Socket connected!");
    });

    socket.on("disconnect", () => {
      console.log("Socket disconnected.");
    });

    socket.on("newMessage", (message) => {
      console.log(message);
      setMessage(message);
    });
  }, []);

  const onClickParagraph = () => {
    console.log("Paragraph clicked.");
    socket.emit("newMessage", String(Math.random()));
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>D&amp;D UI v2</h1>

        <p className={styles.description} onClick={onClickParagraph}>
          Test!
        </p>

        <p className={styles.description}>Message: {message}</p>
      </main>
    </div>
  );
};

export default Home;
